INSERT INTO store_products(name, description, created) VALUES ('NUMBER 1', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 2', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 10', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 6', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 7', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 8','kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 3', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 4','kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 5', 'kind of nice thing', CURRENT_DATE());
INSERT INTO store_products(name, description, created) VALUES ('NUMBER 9', 'kind of nice thing', CURRENT_DATE());